services:
  database:
    container_name: db-postgres
    image: postgres:18-alpine
    platform: linux/arm64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # default: /var/lib/postgresql/data better in a subfolder for volume mounts
      # see https://hub.docker.com/_/postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  minio:
    container_name: minio-s3
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    hostname: minio
    ports:
      # outside:inside
      - 9099:9000
      - 9091:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root421-
    volumes:
      - .minio:/data
